BuscadorBundle\Entity\Entrada:
    type: entity
    table: entradas
    repositoryClass: BuscadorBundle\Repository\EntradaRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titulo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        contenido:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        imagen1:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        latitud:
            type: float
            nullable: true
            precision: 10
            scale: 7
        longitud:
            type: float
            nullable: true
            precision: 10
            scale: 7
        preferencia:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
