BuscadorBundle\Entity\Etiqueta:
    type: entity
    table: etiquetas
    repositoryClass: BuscadorBundle\Repository\EtiquetaRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        estadistica:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
