buscador_buscar:
    path:     /
    defaults: { _controller: BuscadorBundle:Buscar:buscar }

buscador_resultados:
    path:     /resultados
    defaults: { _controller: BuscadorBundle:Buscar:resultados }
    
buscador_entrada:
    path:     /resultados/{id}
    defaults: { _controller: BuscadorBundle:Buscar:mostrarEntrada }
    
login:
    path: /login
    defaults: { _controller: BuscadorBundle:Usuario:login}
    
login_check:
    path: /login_check
    
logout:
    path: /logout

inicio:
    path: admin/inicio
    defaults: { _controller: BuscadorBundle:Usuario:inicio}
    
crear_admin:
    path: /admin/crear
    defaults: { _controller: BuscadorBundle:Usuario:creaAdmin}

listar_admins:
    path: /admin/listar
    defaults: { _controller: BuscadorBundle:Usuario:listarAdmins}
        
eliminar_admin:
    path: /admin/eliminar/{id}
    defaults: { _controller: BuscadorBundle:Usuario:eliminarAdmin}
    
editar_admin:
    path: /admin/editar/{id}
    defaults: { _controller: BuscadorBundle:Usuario:editarAdmin}
    
crear_etiqueta:
    path: /etiqueta/crear
    defaults: { _controller: BuscadorBundle:Etiqueta:crearEtiqueta}
    
listar_etiquetas:
    path: /etiqueta/listar
    defaults: { _controller: BuscadorBundle:Etiqueta:listarEtiquetas}
    
editar_etiqueta:
    path: /etiqueta/editar/{id}
    defaults: { _controller: BuscadorBundle:Etiqueta:editarEtiqueta}
    
crear_entrada:
    path: /entrada/crear
    defaults: { _controller: BuscadorBundle:Entrada:crearEntrada}
    
listar_entradas:
    path: /entrada/listar
    defaults: { _controller: BuscadorBundle:Entrada:listarTodasEntradas}
    
editar_entrada:
    path: /entrada/editar/{id}
    defaults: { _controller: BuscadorBundle:Entrada:editarEntrada}
    
eliminar_entrada:
    path: /entrada/eliminar/{id}
    defaults: { _controller: BuscadorBundle:Entrada:eliminarEntrada}
    
buscar_entrada:
    path: /entrada/buscar
    defaults: { _controller: BuscadorBundle:Entrada:buscarEntrada}
    
pdf_entrada:
    path: /entrada/pdf/{id}
    defaults: { _controller: BuscadorBundle:Buscar:entradaPdf}
    
mostrar_estadisticas:
    path: /mostrar/estadisticas
    defaults: { _controller: BuscadorBundle:Estadisticas:mostrar}