usuarios_homepage:
    path:     /admin
    defaults: { _controller: UsuariosBundle:Default:index }
    
login:
    path: /login
    defaults: { _controller: UsuariosBundle:Usuario:login}
    
login_check:
    path: /login_check
    
logout:
    path: /logout

inicio:
    path: /admin/inicio
    defaults: { _controller: UsuariosBundle:Usuario:inicio}
    
crear_admin:
    path: /admin/crear
    defaults: { _controller: UsuariosBundle:Usuario:creaAdmin}

listar_admins:
    path: /admin/listar
    defaults: { _controller: UsuariosBundle:Usuario:listarAdmins}
        
eliminar_admin:
    path: /admin/eliminar/{id}
    defaults: { _controller: UsuariosBundle:Usuario:eliminarAdmin}
    
editar_admin:
    path: /admin/editar/{id}
    defaults: { _controller: UsuariosBundle:Usuario:editarAdmin}